version: '3.8'

networks:
  gemfire-cache:
    external: true

services:
  gemfire-console:
    image: gemfire/gemfire-management-console:latest
    ports:
      - "7070:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/" ]
      interval: 30s
      start_interval: 5s
      start_period: 20s
      retries: 5
    networks: [ gemfire-cache ]
  # ============================================
  # Prometheus
  # ============================================
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    networks:
      - gemfire-cache
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
    restart: unless-stopped

  # ============================================
  # Grafana
  # ============================================
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    networks:
      - gemfire-cache
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    restart: unless-stopped
    depends_on:
      - prometheus

volumes:
  prometheus-data:
  grafana-data:
